//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Samraksh_Mel.h"

CLR_RT_HeapBlock_NativeEventDispatcher *AI_ne_Context;
UINT64 AI_ne_userData;


static HRESULT Initialize_AI_Driver( CLR_RT_HeapBlock_NativeEventDispatcher *pContext, UINT64 userData ){
	AI_ne_Context = pContext;
	AI_ne_userData = userData;
	return S_OK;
}

static HRESULT  EnableDisable_AI_Driver( CLR_RT_HeapBlock_NativeEventDispatcher *pContext, bool fEnable ){
	return S_OK;
}

static HRESULT Cleanup_AI_Driver( CLR_RT_HeapBlock_NativeEventDispatcher *pContext ){
	AI_ne_Context = NULL;
	AI_ne_userData = 0;
	CleanupNativeEventsFromHALQueue( pContext );
	return S_OK;
}

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::Initialize___BOOLEAN__I4,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::Uninitialize___BOOLEAN,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::GetResultData___BOOLEAN__SZARRAY_R4,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::start_audio_interference___BOOLEAN__I4,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::stop_audio_interference___BOOLEAN,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_Mel =
{
    "Samraksh_Mel", 
    0x1B283CDB,
    method_lookup
};

static const CLR_RT_DriverInterruptMethods g_CLR_AI_DriverMethods =
{
  Initialize_AI_Driver,
  EnableDisable_AI_Driver,
  Cleanup_AI_Driver
};



const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_AICallback  =
{
    "AICallback",
    DRIVER_INTERRUPT_METHODS_CHECKSUM,
    &g_CLR_AI_DriverMethods
};
