//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Samraksh_Mel.h"

CLR_RT_HeapBlock_NativeEventDispatcher *Net_ne_Context;
UINT64 Net_ne_userData;
CLR_RT_HeapBlock_NativeEventDispatcher *AI_ne_Context;
UINT64 AI_ne_userData;

static HRESULT Initialize_Net_Driver( CLR_RT_HeapBlock_NativeEventDispatcher *pContext, UINT64 userData ){
	Net_ne_Context = pContext;
	Net_ne_userData = userData;
	return S_OK;
}

static HRESULT  EnableDisable_Net_Driver( CLR_RT_HeapBlock_NativeEventDispatcher *pContext, bool fEnable ){
	return S_OK;
}

static HRESULT Cleanup_Net_Driver( CLR_RT_HeapBlock_NativeEventDispatcher *pContext ){
	Net_ne_Context = NULL;
	Net_ne_userData = 0;
	CleanupNativeEventsFromHALQueue( pContext );
	return S_OK;
}

static HRESULT Initialize_AI_Driver( CLR_RT_HeapBlock_NativeEventDispatcher *pContext, UINT64 userData ){
	AI_ne_Context = pContext;
	AI_ne_userData = userData;
	return S_OK;
}

static HRESULT  EnableDisable_AI_Driver( CLR_RT_HeapBlock_NativeEventDispatcher *pContext, bool fEnable ){
	return S_OK;
}

static HRESULT Cleanup_AI_Driver( CLR_RT_HeapBlock_NativeEventDispatcher *pContext ){
	AI_ne_Context = NULL;
	AI_ne_userData = 0;
	CleanupNativeEventsFromHALQueue( pContext );
	return S_OK;
}

static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::Initialize___BOOLEAN__I4,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::Uninitialize___BOOLEAN,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::GetResultData___BOOLEAN__SZARRAY_R4,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::start_audio_interference___BOOLEAN__I4,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::stop_audio_interference___BOOLEAN,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Samraksh_Mel_Samraksh_Mel_MACBase::RemovePacket___SamrakshMelDeviceStatus,
    Library_Samraksh_Mel_Samraksh_Mel_MACBase::PendingReceivePacketCount___U1,
    Library_Samraksh_Mel_Samraksh_Mel_MACBase::PendingSendPacketCount___U1,
    Library_Samraksh_Mel_Samraksh_Mel_MACBase::Send___SamrakshMelNetOpStatus__U2__SZARRAY_U1__U2__U2,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Samraksh_Mel_Samraksh_Mel_MACBase::UnInitialize___SamrakshMelDeviceStatus,
    Library_Samraksh_Mel_Samraksh_Mel_MACBase::InternalInitialize___SamrakshMelDeviceStatus__SZARRAY_U1__U1,
    Library_Samraksh_Mel_Samraksh_Mel_MACBase::InternalReConfigure___SamrakshMelDeviceStatus__SZARRAY_U1,
    Library_Samraksh_Mel_Samraksh_Mel_MACBase::GetNextPacket___SamrakshMelDeviceStatus__SZARRAY_U1,
    Library_Samraksh_Mel_Samraksh_Mel_MACBase::GetNeighborInternal___SamrakshMelDeviceStatus__U2__SZARRAY_U1,
    Library_Samraksh_Mel_Samraksh_Mel_MACBase::GetNeighborListInternal___SamrakshMelDeviceStatus__SZARRAY_U2,
    Library_Samraksh_Mel_Samraksh_Mel_MACBase::GetMACNeighborListInternal___SamrakshMelDeviceStatus__SZARRAY_U2,
    NULL,
    NULL,
    Library_Samraksh_Mel_Samraksh_Mel_MACBase::DeletePacketWithIndexInternal___SamrakshMelDeviceStatus__U2,
    Library_Samraksh_Mel_Samraksh_Mel_MACBase::GetPacketWithIndex___SamrakshMelDeviceStatus__SZARRAY_U1__U1__U2,
    Library_Samraksh_Mel_Samraksh_Mel_MACBase::GetPacketSizeWithIndex___SamrakshMelDeviceStatus__BYREF_U1__U2,
    NULL,
    NULL,
    NULL,
    Library_Samraksh_Mel_Samraksh_Mel_MACBase::EnqueueToSend___U2__U2__U1__SZARRAY_U1__U2__U2,
    Library_Samraksh_Mel_Samraksh_Mel_MACBase::EnqueueToSend___U2__U2__U1__SZARRAY_U1__U2__U2__U4,
    Library_Samraksh_Mel_Samraksh_Mel_MACBase::Send___SamrakshMelNetOpStatus__U2__SZARRAY_U1__U2__U2__U4,
    NULL,
    Library_Samraksh_Mel_Samraksh_Mel_MACBase::Send___SamrakshMelNetOpStatus__U2__U1__SZARRAY_U1__U2__U2,
    NULL,
    Library_Samraksh_Mel_Samraksh_Mel_MACBase::Send___SamrakshMelNetOpStatus__U2__U1__SZARRAY_U1__U2__U2__U4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Samraksh_Mel_Samraksh_Mel_Radio_Radio_802_15_4_Base::TurnOnRx___SamrakshMelDeviceStatus__U1,
    Library_Samraksh_Mel_Samraksh_Mel_Radio_Radio_802_15_4_Base::Sleep___SamrakshMelDeviceStatus__U1__U1,
    Library_Samraksh_Mel_Samraksh_Mel_Radio_Radio_802_15_4_Base::ClearChannelAssesment___BOOLEAN__U1,
    Library_Samraksh_Mel_Samraksh_Mel_Radio_Radio_802_15_4_Base::ClearChannelAssesment___BOOLEAN__U1__U2,
    Library_Samraksh_Mel_Samraksh_Mel_Radio_Radio_802_15_4_Base::PreLoad___SamrakshMelNetOpStatus__SZARRAY_U1__U2,
    Library_Samraksh_Mel_Samraksh_Mel_Radio_Radio_802_15_4_Base::SendStrobe___SamrakshMelNetOpStatus__U1__U2,
    Library_Samraksh_Mel_Samraksh_Mel_Radio_Radio_802_15_4_Base::Send___SamrakshMelNetOpStatus__U1__SZARRAY_U1__U2,
    Library_Samraksh_Mel_Samraksh_Mel_Radio_Radio_802_15_4_Base::SendTimeStamped___SamrakshMelNetOpStatus__U1__SZARRAY_U1__U2__U4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Samraksh_Mel_Samraksh_Mel_Radio_Radio_802_15_4_Base::SetRadioName___SamrakshMelDeviceStatus__U1,
    Library_Samraksh_Mel_Samraksh_Mel_Radio_Radio_802_15_4_Base::SetTxPower___SamrakshMelDeviceStatus__U1__I4,
    Library_Samraksh_Mel_Samraksh_Mel_Radio_Radio_802_15_4_Base::SetChannel___SamrakshMelDeviceStatus__U1__I4,
    Library_Samraksh_Mel_Samraksh_Mel_Radio_Radio_802_15_4_Base::GetRadioAddress___U2__U1,
    Library_Samraksh_Mel_Samraksh_Mel_Radio_Radio_802_15_4_Base::SetRadioAddress___BOOLEAN__U1__U2,
    Library_Samraksh_Mel_Samraksh_Mel_Radio_Radio_802_15_4_Base::UnInitialize___SamrakshMelDeviceStatus__U1,
    Library_Samraksh_Mel_Samraksh_Mel_Radio_Radio_802_15_4_Base::TurnOffRx___SamrakshMelDeviceStatus__U1,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_Mel =
{
    "Samraksh_Mel", 
    0xCFCD5BA2,
    method_lookup
};

static const CLR_RT_DriverInterruptMethods g_CLR_Radio_802_15_4_DriverMethods =
{
  Initialize_Net_Driver,
  EnableDisable_Net_Driver,
  Cleanup_Net_Driver
};

static const CLR_RT_DriverInterruptMethods g_CLR_OMAC_MAC_DriverMethods =
{
  Initialize_Net_Driver,
  EnableDisable_Net_Driver,
  Cleanup_Net_Driver
};

static const CLR_RT_DriverInterruptMethods g_CLR_MAC_MAC_DriverMethods =
{
  Initialize_Net_Driver,
  EnableDisable_Net_Driver,
  Cleanup_Net_Driver
};

static const CLR_RT_DriverInterruptMethods g_CLR_AI_DriverMethods =
{
  Initialize_AI_Driver,
  EnableDisable_AI_Driver,
  Cleanup_AI_Driver
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_RadioCallback_802_15_4  =
{
    "RadioCallback_802_15_4",
    DRIVER_INTERRUPT_METHODS_CHECKSUM,
    &g_CLR_Radio_802_15_4_DriverMethods
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_OMACCallback  =
{
    "OMACCallback",
    DRIVER_INTERRUPT_METHODS_CHECKSUM,
    &g_CLR_OMAC_MAC_DriverMethods
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_MACCallback  =
{
    "MACCallback",
    DRIVER_INTERRUPT_METHODS_CHECKSUM,
    &g_CLR_MAC_MAC_DriverMethods
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_AICallback  =
{
    "AICallback",
    DRIVER_INTERRUPT_METHODS_CHECKSUM,
    &g_CLR_AI_DriverMethods
};
