//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SAMRAKSHEMOTEREALTIME_H_
#define _SAMRAKSHEMOTEREALTIME_H_

#include <TinyCLR_Interop.h>
struct Library_SamrakshEmoteRealtime_Samraksh_eMote_RealTime_Timer
{
    TINYCLR_NATIVE_DECLARE(Dispose___VOID);
    TINYCLR_NATIVE_DECLARE(Change___BOOLEAN__U4__U4);
    TINYCLR_NATIVE_DECLARE(GenerateInterrupt___VOID);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_eMote_RealTime;

#endif  //_SAMRAKSHEMOTEREALTIME_H_
