//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Samraksh_eMote_ProgramManager.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    Library_Samraksh_eMote_ProgramManager_Samraksh_eMote_ProgramManager_ProgramManager::UpdaterStart___BOOLEAN,
    Library_Samraksh_eMote_ProgramManager_Samraksh_eMote_ProgramManager_ProgramManager::UpdaterStart___BOOLEAN__U4,
    Library_Samraksh_eMote_ProgramManager_Samraksh_eMote_ProgramManager_ProgramManager::UpdaterSetDestination___VOID__U2,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_eMote_ProgramManager =
{
    "Samraksh_eMote_ProgramManager", 
    0xDD4C0E62,
    method_lookup
};

