//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "SamrakshEmoteDSP.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Statistics::Sum___U8__SZARRAY_U1,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Statistics::Sum___U8__SZARRAY_U2,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Statistics::Sum___U8__SZARRAY_U4,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Statistics::Sum___U8__SZARRAY_U8,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Statistics::Median___U1__SZARRAY_U1,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Statistics::Median___U2__SZARRAY_U2,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Statistics::Median___U4__SZARRAY_U4,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Statistics::Median___U8__SZARRAY_U8,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Statistics::Mode___U1__SZARRAY_U1,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Statistics::Mode___U2__SZARRAY_U2,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Statistics::Mode___U4__SZARRAY_U4,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Statistics::Mode___U8__SZARRAY_U8,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Statistics::Variance___R8__SZARRAY_U1,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Statistics::Variance___R8__SZARRAY_U2,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Statistics::Variance___R8__SZARRAY_U4,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Statistics::Variance___R8__SZARRAY_U8,
    NULL,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Transforms::FFT___BOOLEAN__SZARRAY_U1__SZARRAY_U1__U2,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Transforms::FFT___BOOLEAN__SZARRAY_U2__SZARRAY_U2__U2,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Transforms::FFT___BOOLEAN__SZARRAY_U4__SZARRAY_U4__U2,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Transforms::FFT___BOOLEAN__SZARRAY_I2__SZARRAY_I2__U2,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Transforms::IFFT___BOOLEAN__SZARRAY_U1__SZARRAY_U1__U2,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Transforms::IFFT___BOOLEAN__SZARRAY_U2__SZARRAY_U2__U2,
    Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Transforms::IFFT___BOOLEAN__SZARRAY_U4__SZARRAY_U4__U2,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_eMote_DSP =
{
    "Samraksh_eMote_DSP", 
    0xE3F2AD8A,
    method_lookup
};

