//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SAMRAKSHEMOTEDSP_H_
#define _SAMRAKSHEMOTEDSP_H_

#include <TinyCLR_Interop.h>
struct Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Statistics
{
    TINYCLR_NATIVE_DECLARE(Sum___U8__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(Sum___U8__SZARRAY_U2);
    TINYCLR_NATIVE_DECLARE(Sum___U8__SZARRAY_U4);
    TINYCLR_NATIVE_DECLARE(Sum___U8__SZARRAY_U8);
    TINYCLR_NATIVE_DECLARE(Median___U1__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(Median___U2__SZARRAY_U2);
    TINYCLR_NATIVE_DECLARE(Median___U4__SZARRAY_U4);
    TINYCLR_NATIVE_DECLARE(Median___U8__SZARRAY_U8);
    TINYCLR_NATIVE_DECLARE(Mode___U1__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(Mode___U2__SZARRAY_U2);
    TINYCLR_NATIVE_DECLARE(Mode___U4__SZARRAY_U4);
    TINYCLR_NATIVE_DECLARE(Mode___U8__SZARRAY_U8);
    TINYCLR_NATIVE_DECLARE(Variance___R8__SZARRAY_U1);
    TINYCLR_NATIVE_DECLARE(Variance___R8__SZARRAY_U2);
    TINYCLR_NATIVE_DECLARE(Variance___R8__SZARRAY_U4);
    TINYCLR_NATIVE_DECLARE(Variance___R8__SZARRAY_U8);

    //--//

};

struct Library_SamrakshEmoteDSP_Samraksh_eMote_DSP_Transforms
{
    TINYCLR_NATIVE_DECLARE(FFT___BOOLEAN__SZARRAY_U1__SZARRAY_U1__U2);
    TINYCLR_NATIVE_DECLARE(FFT___BOOLEAN__SZARRAY_U2__SZARRAY_U2__U2);
    TINYCLR_NATIVE_DECLARE(FFT___BOOLEAN__SZARRAY_U4__SZARRAY_U4__U2);
    TINYCLR_NATIVE_DECLARE(FFT___BOOLEAN__SZARRAY_I2__SZARRAY_I2__U2);
    TINYCLR_NATIVE_DECLARE(IFFT___BOOLEAN__SZARRAY_U1__SZARRAY_U1__U2);
    TINYCLR_NATIVE_DECLARE(IFFT___BOOLEAN__SZARRAY_U2__SZARRAY_U2__U2);
    TINYCLR_NATIVE_DECLARE(IFFT___BOOLEAN__SZARRAY_U4__SZARRAY_U4__U2);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_eMote_DSP;

#endif  //_SAMRAKSHEMOTEDSP_H_
