//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SAMRAKSHEMOTE_H_
#define _SAMRAKSHEMOTE_H_

#include <TinyCLR_Interop.h>
struct Library_SamrakshEmote_Samraksh_eMote_Algorithm__AcousticDetection
{
    TINYCLR_NATIVE_DECLARE(DetectionCalculation___BOOLEAN__SZARRAY_U2__I4__SZARRAY_R8__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(SetDetectionParameters___BOOLEAN__I4__I4);

    //--//

};

struct Library_SamrakshEmote_Samraksh_eMote_Algorithm__DecisionFunction
{
    TINYCLR_NATIVE_DECLARE(Initialize___VOID__U2__U2__R4__R4__SZARRAY_R4__SZARRAY_R4__SZARRAY_R4);
    TINYCLR_NATIVE_DECLARE(NormalizeFeatureVector___VOID__SZARRAY_R4__SZARRAY_I4);
    TINYCLR_NATIVE_DECLARE(Decide___R4__SZARRAY_I4);

    //--//

};

struct Library_SamrakshEmote_Samraksh_eMote_Algorithm__RadarDetection
{
    TINYCLR_NATIVE_DECLARE(Initialize___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(Uninitialize___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(DetectionCalculation___BOOLEAN__SZARRAY_U2__SZARRAY_U2__SZARRAY_U2__I4);
    TINYCLR_NATIVE_DECLARE(DetectionCalculation___BOOLEAN__SZARRAY_U2__SZARRAY_U2__I4);
    TINYCLR_NATIVE_DECLARE(SetDetectionParameters___BOOLEAN__SamraksheMoteRADARNOISECONTROL__R8__R8__U2__U2__U2__U2__U2);
    TINYCLR_NATIVE_DECLARE(GetBackgroundNoiseLevel___I4__SamraksheMoteRADARNOISEREQUEST);
    TINYCLR_NATIVE_DECLARE(ResetBackgroundNoiseTracking___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(GetIQRejectionLevel___I4);
    TINYCLR_NATIVE_DECLARE(GetLastUnwrap___I4__SamraksheMoteRADARNOISEREQUEST);
    TINYCLR_NATIVE_DECLARE(GetWindowOverThreshold___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(CurrentDetectionFinished___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(GetNetDisplacement___I4__SamraksheMoteSAMPLEWINDOWPORTION);
    TINYCLR_NATIVE_DECLARE(GetAbsoluteDisplacement___I4__SamraksheMoteSAMPLEWINDOWPORTION);
    TINYCLR_NATIVE_DECLARE(GetDisplacementRange___I4__SamraksheMoteSAMPLEWINDOWPORTION);
    TINYCLR_NATIVE_DECLARE(GetCountOverTarget___I4);

    //--//

};

struct Library_SamrakshEmote_Samraksh_eMote_NonVolatileMemory_DataReference
{
    static const int FIELD__dStore = 1;
    static const int FIELD__dataId = 2;
    static const int FIELD__referenceSize = 3;
    static const int FIELD__dataLocationOnStorage = 4;
    static const int FIELD__referenceDataType = 5;
    static const int FIELD__dataType = 6;
    static const int FIELD__dataTypeByte = 7;
    static const int FIELD__dataTypeUInt16 = 8;
    static const int FIELD__dataTypeUInt32 = 9;

    TINYCLR_NATIVE_DECLARE(GetDataReference___I4__U4);
    TINYCLR_NATIVE_DECLARE(GetDataLocation___I4__U4);
    TINYCLR_NATIVE_DECLARE(LookupDataType___I4__U4);
    TINYCLR_NATIVE_DECLARE(LookupDataSize___I4__U4);
    TINYCLR_NATIVE_DECLARE(DeleteData___BOOLEAN__U4);
    TINYCLR_NATIVE_DECLARE(CreateData___I4__U4__U1);
    TINYCLR_NATIVE_DECLARE(CreateData___I4__U4__U2);
    TINYCLR_NATIVE_DECLARE(CreateData___I4__U4__U4);
    TINYCLR_NATIVE_DECLARE(GetDataID___U4);
    TINYCLR_NATIVE_DECLARE(GetLastDatastoreStatus___I4);
    TINYCLR_NATIVE_DECLARE(DisposeNativeMemoryPointer___BOOLEAN__U4);

    //--//

};

struct Library_SamrakshEmote_Samraksh_eMote_NonVolatileMemory_DataStore
{
    static const int FIELD_STATIC__DSInstance = 0;
    static const int FIELD_STATIC__syncObject = 1;
    static const int FIELD_STATIC__dataStoreInstances = 2;

    static const int FIELD__storageType = 1;

    TINYCLR_NATIVE_DECLARE(CreateDataStore___I4__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(GetMaxAllocationSize___I4);
    TINYCLR_NATIVE_DECLARE(GetTotalSpace___I4);
    TINYCLR_NATIVE_DECLARE(GetUsedBytes___I4);
    TINYCLR_NATIVE_DECLARE(GetFreeBytes___I4);
    TINYCLR_NATIVE_DECLARE(GetReadAllDataIds___I4__SZARRAY_I4__I4__I4);
    TINYCLR_NATIVE_DECLARE(GetCountOfDataIds___I4);
    TINYCLR_NATIVE_DECLARE(DeleteAll___I4);
    TINYCLR_NATIVE_DECLARE(EraseAllBlocks___I4);
    TINYCLR_NATIVE_DECLARE(DataStoreGC___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(GetReadWriteStatus___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(GetLastDatastoreStatus___I4);
    TINYCLR_NATIVE_DECLARE(WriteRaw___I4__U4__SZARRAY_U1__U4__U4__U1__I4);
    TINYCLR_NATIVE_DECLARE(WriteRaw___I4__U4__SZARRAY_U1__U4__U4__U2__I4);
    TINYCLR_NATIVE_DECLARE(WriteRaw___I4__U4__SZARRAY_U1__U4__U4__U4__I4);
    TINYCLR_NATIVE_DECLARE(ReadRaw___I4__U4__SZARRAY_U1__U4__U4__U1__I4);
    TINYCLR_NATIVE_DECLARE(ReadRaw___I4__U4__SZARRAY_U1__U4__U4__U2__I4);
    TINYCLR_NATIVE_DECLARE(ReadRaw___I4__U4__SZARRAY_U1__U4__U4__U4__I4);

    //--//

};

struct Library_SamrakshEmote_Samraksh_eMote_Platform
{
    TINYCLR_NATIVE_DECLARE(GetPlatformTypeInternal___STATIC__SamraksheMotePLATFORMTYPE);

    //--//

};

struct Library_SamrakshEmote_Samraksh_eMote_RadarInterface
{
    static const int FIELD_STATIC___radarInternal = 3;
    static const int FIELD_STATIC___myCallback = 4;

    TINYCLR_NATIVE_DECLARE(TurnOn___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(TurnOff___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(Blind___BOOLEAN);

    //--//

};

struct Library_SamrakshEmote_Samraksh_eMote_RadarInternal
{
    TINYCLR_NATIVE_DECLARE(ConfigureFPGADetectionPrivate___BOOLEAN__SZARRAY_U2__SZARRAY_U2__SZARRAY_I2__SZARRAY_I2__SZARRAY_I2__SZARRAY_BOOLEAN__U4);
    TINYCLR_NATIVE_DECLARE(CurrentDetectionFinished___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(setContinueToSendCount___VOID__U2);
    TINYCLR_NATIVE_DECLARE(getContinueToSendCount___U2);
    TINYCLR_NATIVE_DECLARE(setNumLookAheadWindows___VOID__U2);
    TINYCLR_NATIVE_DECLARE(getNumLookAheadWindows___U2);
    TINYCLR_NATIVE_DECLARE(getNumDetectionsInWindow___U2);
    TINYCLR_NATIVE_DECLARE(getTotalRotationsofWindow___I2);
    TINYCLR_NATIVE_DECLARE(SetProcessingInProgress___VOID__BOOLEAN);
    TINYCLR_NATIVE_DECLARE(Init___STATIC__I4__I4);
    TINYCLR_NATIVE_DECLARE(Uninit___STATIC__BOOLEAN);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_eMote;

#endif  //_SAMRAKSHEMOTE_H_
