//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Samraksh_Mel.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::Initialize___BOOLEAN__I4,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::Uninitialize___BOOLEAN,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::GetResultData___BOOLEAN__SZARRAY_R4,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::start_audio_inference___BOOLEAN__I4,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::stop_audio_inference___BOOLEAN,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_Mel =
{
    "Samraksh_Mel", 
    0x4314F32E,
    method_lookup
};

