//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#ifndef _SAMRAKSH_MEL_H_
#define _SAMRAKSH_MEL_H_

#include <TinyCLR_Interop.h>
struct Library_Samraksh_Mel_Samraksh_Mel_AudioInterface
{
    static const int FIELD__callbackDataSize = 5;
    static const int FIELD__audio_inference_callback = 6;

    TINYCLR_NATIVE_DECLARE(Initialize___BOOLEAN__I4);
    TINYCLR_NATIVE_DECLARE(Uninitialize___BOOLEAN);
    TINYCLR_NATIVE_DECLARE(GetResultData___BOOLEAN__SZARRAY_R4);
    TINYCLR_NATIVE_DECLARE(start_audio_interference___BOOLEAN__I4);
    TINYCLR_NATIVE_DECLARE(stop_audio_interference___BOOLEAN);

    //--//

};



extern const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_Mel;

#endif  //_SAMRAKSH_MEL_H_
