//-----------------------------------------------------------------------------
//
//    ** DO NOT EDIT THIS FILE! **
//    This file was generated by a tool
//    re-running the tool will overwrite this file.
//
//-----------------------------------------------------------------------------


#include "Samraksh_Mel.h"


static const CLR_RT_MethodHandler method_lookup[] =
{
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::set_fir_taps_internal___BOOLEAN__U4__SZARRAY_R4,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::set_model_recording_internal___VOID__BOOLEAN__BOOLEAN,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::Initialize___BOOLEAN,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::Uninitialize___BOOLEAN,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::GetResultData___BOOLEAN__BYREF_R4__SZARRAY_R4__SZARRAY_R4,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::start_audio_inference___BOOLEAN,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::stop_audio_inference___VOID,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::set_ml_duty_cycle___BOOLEAN__U4__U4,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::set_raw_data_output___BOOLEAN__BOOLEAN,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::set_dB_thresh___BOOLEAN__R4,
    Library_Samraksh_Mel_Samraksh_Mel_AudioInterface::set_time_interval___BOOLEAN__U4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Samraksh_Mel_Samraksh_Mel_UsbSerialInterface::BytesInBuffer___U4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    Library_Samraksh_Mel_Samraksh_Mel_UsbSerialInterface::mel_serial_tx___I4__SZARRAY_U1__U4__I4,
    Library_Samraksh_Mel_Samraksh_Mel_UsbSerialInterface::mel_serial_rx___I4__SZARRAY_U1__U4,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
    NULL,
};

const CLR_RT_NativeAssemblyData g_CLR_AssemblyNative_Samraksh_Mel =
{
    "Samraksh_Mel", 
    0x8F1BAEEF,
    method_lookup
};

